### ISSUE TITLE
Clean up running conformance tests

### ISSUE THREAD

**Issue by wmdietl** [eisop/jspecify-conformance#11]
#10 adds supports for running on conformance tests.

The fastest way was to duplicate the fields and have two `@Test` methods.
This seems a bit ugly, as the `build.gradle` file looks like two separate tests are run with different configurations.
But both tests are run with the same environment, just the different tests look at different parts.
Maybe this could be done more nicely, at least by removing the fields and setting this more cleanly.

Also note that `deps` isn't needed for `samples`, so clean that up, too.

**Comment by Haibo-S** [comment]
Please refer to this pull request: [https://github.com/eisop/jspecify-conformance/pull/24](https://github.com/eisop/jspecify-conformance/pull/24)
